# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/apropos_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_apropos(object):
    def setupUi(self, apropos):
        apropos.setObjectName("apropos")
        apropos.resize(316, 88)
        self.centralwidget = QtWidgets.QWidget(apropos)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        apropos.setCentralWidget(self.centralwidget)

        self.retranslateUi(apropos)
        QtCore.QMetaObject.connectSlotsByName(apropos)

    def retranslateUi(self, apropos):
        _translate = QtCore.QCoreApplication.translate
        apropos.setWindowTitle(_translate("apropos", "À Propos"))
        self.label.setText(_translate("apropos", "<html><head/><body><p align=\"center\">Version 1.0</p></body></html>"))
        self.label_2.setText(_translate("apropos", "<html><head/><body><p align=\"center\">Herman Adrien</p></body></html>"))
        self.label_3.setText(_translate("apropos", "<html><head/><body><p align=\"center\">Avril 2021</p></body></html>"))
