# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/faux_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MauvRep(object):
    def setupUi(self, MauvRep):
        MauvRep.setObjectName("MauvRep")
        MauvRep.resize(557, 191)
        self.centralwidget = QtWidgets.QWidget(MauvRep)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.motcorrige = QtWidgets.QLabel(self.centralwidget)
        self.motcorrige.setObjectName("motcorrige")
        self.horizontalLayout.addWidget(self.motcorrige)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.mottappe = QtWidgets.QLineEdit(self.centralwidget)
        self.mottappe.setAcceptDrops(False)
        self.mottappe.setObjectName("mottappe")
        self.verticalLayout_2.addWidget(self.mottappe)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setObjectName("ok")
        self.horizontalLayout_3.addWidget(self.ok)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MauvRep.setCentralWidget(self.centralwidget)

        self.retranslateUi(MauvRep)
        QtCore.QMetaObject.connectSlotsByName(MauvRep)

    def retranslateUi(self, MauvRep):
        _translate = QtCore.QCoreApplication.translate
        MauvRep.setWindowTitle(_translate("MauvRep", "Mauvaise Réponse"))
        self.label.setText(_translate("MauvRep", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ff0000;\">Faux!</span></p></body></html>"))
        self.label_2.setText(_translate("MauvRep", "<html><head/><body><p><span style=\" font-size:14pt;\">Correction: </span></p></body></html>"))
        self.motcorrige.setText(_translate("MauvRep", "<html><head/><body><p><span style=\" font-size:14pt;\">Mot Corrigé</span></p></body></html>"))
        self.label_4.setText(_translate("MauvRep", "Tapes le mot:"))
        self.ok.setText(_translate("MauvRep", "OK"))
