# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/liste_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListeWindow(object):
    def setupUi(self, ListeWindow):
        ListeWindow.setObjectName("ListeWindow")
        ListeWindow.resize(551, 339)
        self.centralwidget = QtWidgets.QWidget(ListeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setFrameShape(QtWidgets.QFrame.Box)
        self.tableView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableView.setLineWidth(3)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setTabKeyNavigation(False)
        self.tableView.setProperty("showDropIndicator", False)
        self.tableView.setDragDropOverwriteMode(False)
        self.tableView.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView.setWordWrap(False)
        self.tableView.setCornerButtonEnabled(False)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        ListeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ListeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 30))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFichiers = QtWidgets.QMenu(self.menubar)
        self.menuFichiers.setObjectName("menuFichiers")
        ListeWindow.setMenuBar(self.menubar)
        self.actionQuitter = QtWidgets.QAction(ListeWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionConvertir_une_liste_de_vocabualire_en_pdf = QtWidgets.QAction(ListeWindow)
        self.actionConvertir_une_liste_de_vocabualire_en_pdf.setObjectName("actionConvertir_une_liste_de_vocabualire_en_pdf")
        self.actionOuvrir_une_liste_de_vocabulaire = QtWidgets.QAction(ListeWindow)
        self.actionOuvrir_une_liste_de_vocabulaire.setObjectName("actionOuvrir_une_liste_de_vocabulaire")
        self.menuFichiers.addAction(self.actionOuvrir_une_liste_de_vocabulaire)
        self.menuFichiers.addSeparator()
        self.menuFichiers.addAction(self.actionConvertir_une_liste_de_vocabualire_en_pdf)
        self.menuFichiers.addSeparator()
        self.menuFichiers.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuFichiers.menuAction())

        self.retranslateUi(ListeWindow)
        QtCore.QMetaObject.connectSlotsByName(ListeWindow)

    def retranslateUi(self, ListeWindow):
        _translate = QtCore.QCoreApplication.translate
        ListeWindow.setWindowTitle(_translate("ListeWindow", "Liste de vocabulaire"))
        self.label.setText(_translate("ListeWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">Liste ouverte:</span></p></body></html>"))
        self.label_2.setText(_translate("ListeWindow", "LISTE"))
        self.menuFichiers.setTitle(_translate("ListeWindow", "Fichiers"))
        self.actionQuitter.setText(_translate("ListeWindow", "Quitter"))
        self.actionQuitter.setShortcut(_translate("ListeWindow", "Ctrl+Q"))
        self.actionConvertir_une_liste_de_vocabualire_en_pdf.setText(_translate("ListeWindow", "Convertir une liste de vocabualire en pdf"))
        self.actionConvertir_une_liste_de_vocabualire_en_pdf.setShortcut(_translate("ListeWindow", "Ctrl+C"))
        self.actionOuvrir_une_liste_de_vocabulaire.setText(_translate("ListeWindow", "Ouvrir une liste de vocabulaire"))
        self.actionOuvrir_une_liste_de_vocabulaire.setShortcut(_translate("ListeWindow", "Ctrl+O"))
