# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/modifier_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModifierListe(object):
    def setupUi(self, ModifierListe):
        ModifierListe.setObjectName("ModifierListe")
        ModifierListe.resize(800, 272)
        self.centralwidget = QtWidgets.QWidget(ModifierListe)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.openvoca = QtWidgets.QPushButton(self.centralwidget)
        self.openvoca.setObjectName("openvoca")
        self.verticalLayout.addWidget(self.openvoca)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fichierouvert = QtWidgets.QLabel(self.centralwidget)
        self.fichierouvert.setObjectName("fichierouvert")
        self.horizontalLayout_2.addWidget(self.fichierouvert)
        self.cheminfichier = QtWidgets.QLabel(self.centralwidget)
        self.cheminfichier.setObjectName("cheminfichier")
        self.horizontalLayout_2.addWidget(self.cheminfichier)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.listemot = QtWidgets.QComboBox(self.centralwidget)
        self.listemot.setObjectName("listemot")
        self.verticalLayout.addWidget(self.listemot)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.motedit = QtWidgets.QLineEdit(self.centralwidget)
        self.motedit.setWhatsThis("")
        self.motedit.setObjectName("motedit")
        self.gridLayout.addWidget(self.motedit, 1, 0, 1, 1)
        self.tradedit = QtWidgets.QLineEdit(self.centralwidget)
        self.tradedit.setWhatsThis("")
        self.tradedit.setObjectName("tradedit")
        self.gridLayout.addWidget(self.tradedit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modifmot = QtWidgets.QPushButton(self.centralwidget)
        self.modifmot.setObjectName("modifmot")
        self.horizontalLayout.addWidget(self.modifmot)
        self.supprmot = QtWidgets.QPushButton(self.centralwidget)
        self.supprmot.setObjectName("supprmot")
        self.horizontalLayout.addWidget(self.supprmot)
        self.addmot = QtWidgets.QPushButton(self.centralwidget)
        self.addmot.setWhatsThis("")
        self.addmot.setObjectName("addmot")
        self.horizontalLayout.addWidget(self.addmot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setObjectName("save")
        self.verticalLayout.addWidget(self.save)
        ModifierListe.setCentralWidget(self.centralwidget)

        self.retranslateUi(ModifierListe)
        QtCore.QMetaObject.connectSlotsByName(ModifierListe)

    def retranslateUi(self, ModifierListe):
        _translate = QtCore.QCoreApplication.translate
        ModifierListe.setWindowTitle(_translate("ModifierListe", "Modifier une liste de vocabulaire"))
        self.openvoca.setText(_translate("ModifierListe", "Ouvrir une liste de vocabulaire"))
        self.fichierouvert.setText(_translate("ModifierListe", "<html><head/><body><p align=\"center\"><span style=\" text-decoration: underline;\">Fichier ouvert:</span></p></body></html>"))
        self.cheminfichier.setText(_translate("ModifierListe", "<html><head/><body><p align=\"center\">FICHIER</p></body></html>"))
        self.label_2.setText(_translate("ModifierListe", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Mot</span></p></body></html>"))
        self.label_3.setText(_translate("ModifierListe", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Traduction</span></p></body></html>"))
        self.motedit.setToolTip(_translate("ModifierListe", "Tappez \'Entrer\' pour ajouter un mot à la liste"))
        self.tradedit.setToolTip(_translate("ModifierListe", "Tappez \'Entrer\' pour ajouter un mot à la liste"))
        self.modifmot.setText(_translate("ModifierListe", "Modifier le mot sélectionné dans la liste"))
        self.supprmot.setText(_translate("ModifierListe", "Supprimer le mot sélectionné dans la liste"))
        self.addmot.setToolTip(_translate("ModifierListe", "Tappez \'Entrer\' pour ajouter un mot à la liste"))
        self.addmot.setText(_translate("ModifierListe", "Ajouter le mot à la liste"))
        self.save.setToolTip(_translate("ModifierListe", "Ctrl+S"))
        self.save.setText(_translate("ModifierListe", "Enregistrer le fichier"))
