# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/nouveau_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NouvelleListe(object):
    def setupUi(self, NouvelleListe):
        NouvelleListe.setObjectName("NouvelleListe")
        NouvelleListe.resize(800, 199)
        self.centralwidget = QtWidgets.QWidget(NouvelleListe)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listemot = QtWidgets.QComboBox(self.centralwidget)
        self.listemot.setObjectName("listemot")
        self.verticalLayout.addWidget(self.listemot)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.motedit = QtWidgets.QLineEdit(self.centralwidget)
        self.motedit.setWhatsThis("")
        self.motedit.setObjectName("motedit")
        self.gridLayout.addWidget(self.motedit, 1, 0, 1, 1)
        self.tradedit = QtWidgets.QLineEdit(self.centralwidget)
        self.tradedit.setWhatsThis("")
        self.tradedit.setObjectName("tradedit")
        self.gridLayout.addWidget(self.tradedit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modifmot = QtWidgets.QPushButton(self.centralwidget)
        self.modifmot.setObjectName("modifmot")
        self.horizontalLayout.addWidget(self.modifmot)
        self.supprmot = QtWidgets.QPushButton(self.centralwidget)
        self.supprmot.setObjectName("supprmot")
        self.horizontalLayout.addWidget(self.supprmot)
        self.addmot = QtWidgets.QPushButton(self.centralwidget)
        self.addmot.setWhatsThis("")
        self.addmot.setObjectName("addmot")
        self.horizontalLayout.addWidget(self.addmot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setObjectName("save")
        self.verticalLayout.addWidget(self.save)
        NouvelleListe.setCentralWidget(self.centralwidget)

        self.retranslateUi(NouvelleListe)
        QtCore.QMetaObject.connectSlotsByName(NouvelleListe)

    def retranslateUi(self, NouvelleListe):
        _translate = QtCore.QCoreApplication.translate
        NouvelleListe.setWindowTitle(_translate("NouvelleListe", "Créer une nouvelle liste de vocabulaire"))
        self.label_2.setText(_translate("NouvelleListe", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Mot</span></p></body></html>"))
        self.label_3.setText(_translate("NouvelleListe", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Traduction</span></p></body></html>"))
        self.motedit.setToolTip(_translate("NouvelleListe", "Tappez \'Entrer\' pour ajouter un mot à la liste"))
        self.tradedit.setToolTip(_translate("NouvelleListe", "Tappez \'Entrer\' pour ajouter un mot à la liste"))
        self.modifmot.setText(_translate("NouvelleListe", "Modifier le mot sélectionné dans la liste"))
        self.supprmot.setText(_translate("NouvelleListe", "Supprimer le mot sélectionné dans la liste"))
        self.addmot.setToolTip(_translate("NouvelleListe", "Tappez \'Entrer\' pour ajouter un mot à la liste"))
        self.addmot.setText(_translate("NouvelleListe", "Ajouter le mot à la liste"))
        self.save.setToolTip(_translate("NouvelleListe", "Ctrl+S"))
        self.save.setText(_translate("NouvelleListe", "Enregistrer le fichier"))
